Il ne faut pas modifier le sous type de la commande si l'utilisateur …
tuxgasy/jeedom-tydom pull request #2
Opened 2023-05-05 10:27 UTC by scanab

…l'a customisé

2023-05-05 15:16 UTC, scanab commented
J'ai finalement ajouté l'initialisation avec une configuration par défaut pour les équipements

2023-05-06 08:24 UTC, tuxgasy requested changes
Merci pour ce PR qui va simplifier grandement l'ajout d'autre device.

2023-05-06 08:24 UTC, tuxgasy commented on core/php/jeeTydom.php
> +require_once dirname(__FILE__) . "/../class/tydom.class.php";
Ce n'est pas nécessaire.

2023-05-06 08:44 UTC, scanab commented on core/php/jeeTydom.php
> +require_once dirname(__FILE__) . "/../class/tydom.class.php";
Je m'en doutais un peu, je l'avais mis au début, et j'ai oublié de le retirer avant de commiter 😅

2023-05-06 08:58 UTC, tuxgasy commented on core/config/devices/belmDoor.belmDoor.json
> +      },
Je suis en train de faire le json pour mes équipements.
Vu que les clés name, logicalId et generic_type ne sont pas utilisés, on peut les enlever pour alléger le fichier, non ?

2023-05-07 19:16 UTC, merged

2023-05-09 17:21 UTC, scanab commented on core/config/devices/belmDoor.belmDoor.json
> +      },
Logicalid, je suis d'accord, c'est inutile, la clé de l'entrée Json est déjà suffisante. Pour les autres, non, il faut les garder je pense. Je n'ai pas fait le code qui value les propriétés des objets, juste des commandes infos, c'est pour ça que ce n'est pas utilisé.